export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const RECEIVE_COUNTRIES = "RECEIVE_COUNTRIES";
export const GET_COUNTRY_DETAILS = "GET_COUNTRY_DETAILS";
export const COUNTRIES_FILTERED = "COUNTRIES_FILTERED";
export const SET_SEARCH = "SET_SEARCH";
export const VISIBLE_PAGES = "VISIBLE_PAGES";
export const RESET_CURRENT_PAGE = "RESET_CURRENT_PAGE";
export const API_BASE_URL = "https://restcountries.com/v3.1";
